
namespace ImprovementArsenalPlugin
{
    public partial class IATable
    {
        public static IATable[] List = new IATable[] {
            //小口径主砲
            new IATable { Equip = "10cm連装高角砲", Info = "★0~5\t2+10cm連装高角砲x1\n★6~9\t4+10cm連装高角砲x1\n★max\t6+94式高射装置x1\t⇒10cm高角砲＋高射装置", Days = new string[] {"火","水"}, ShipName = "吹雪改二"},
            new IATable { Equip = "10cm連装高角砲", Info = "★0~5\t2+10cm連装高角砲x1\n★6~9\t4+10cm連装高角砲x1\n★max\t6+94式高射装置x1\t⇒10cm高角砲＋高射装置", Days = new string[] {"日", "月","火","水","木","金","土"}, ShipName = "冬月"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Info = "★0~5\t3\n★6~9\t4+10cm連装高角砲x2", Days = new string[] {"月","火","水","木"}, ShipName = "秋月"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Info = "★0~5\t3\n★6~9\t4+10cm連装高角砲x2", Days = new string[] {"月","火","水","木"}, ShipName = "初月"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Info = "★0~5\t3\n★6~9\t4+10cm連装高角砲x2", Days = new string[] {"日","木","金","土"}, ShipName = "照月"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Info = "★0~5\t3\n★6~9\t4+10cm連装高角砲x2", Days = new string[] {"日","月","金","土"}, ShipName = "涼月"},
            new IATable { Equip = "10cm連装高角砲+高射装置", Info = "★0~5\t3\n★6~9\t4+10cm連装高角砲x2", Days = new string[] {"日","月","金","土"}, ShipName = "冬月"},
            new IATable { Equip = "12cm単装砲", Info = "★0~5\t1+12cm単装砲x1\n★6~9\t1+12cm単装砲x2\n★max\t2+22号対水上電探x1\t⇒12cm単装砲改二", Days = new string[] {"日", "月","火","水","木","金","土"}, ShipName = "睦月"},
            new IATable { Equip = "12cm単装砲", Info = "★0~5\t1+12cm単装砲x1\n★6~9\t1+12cm単装砲x2\n★max\t2+22号対水上電探x1\t⇒12cm単装砲改二", Days = new string[] {"日", "月","火","水","木","金","土"}, ShipName = "如月"},
            new IATable { Equip = "12cm単装砲改二", Info = "★0~5\t2+12cm単装砲x2\n★6~9\t2/4+22号対水上電探x1", Days = new string[] {"月","火","水","木","金"}, ShipName = "睦月改二"},
            new IATable { Equip = "12cm単装砲改二", Info = "★0~5\t2+12cm単装砲x2\n★6~9\t2/4+22号対水上電探x1", Days = new string[] {"日","水","木","金","土"}, ShipName = "如月改二"},
            new IATable { Equip = "12cm単装高角砲E型", Info = "★0~5\t1+12cm単装砲x1\n★6~9\t2+12cm単装高角砲E型x1", Days = new string[] {"木","金","土"}, ShipName = "御蔵"},
            new IATable { Equip = "12cm単装高角砲E型", Info = "★0~5\t1+12cm単装砲x1\n★6~9\t2+12cm単装高角砲E型x1", Days = new string[] {"日","金","土"}, ShipName = "日振"},
            new IATable { Equip = "12cm単装高角砲E型", Info = "★0~5\t1+12cm単装砲x1\n★6~9\t2+12cm単装高角砲E型x1", Days = new string[] {"月","火","水"}, ShipName = "大東"},



            new IATable { Equip = "12.7cm連装砲", Info = "★0~5\n★6~9\t1/2+12.7cm連装砲x1 \n★max\t3/6+12.7cm連装砲x2\t⇒12.7cm連装砲B型改二", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = ""},
            new IATable { Equip = "12.7cm連装砲B型改二", Info = "★0~5\n★6~9\t2/4+12.7cm連装砲x1 \n★max\t4+12.7cm連装砲x3\t⇒12.7cm連装砲C型改二", Days = new string[] {"月","火","水"}, ShipName = "綾波改二"},
            new IATable { Equip = "12.7cm連装砲B型改二", Info = "★0~5\n★6~9\t2/4+12.7cm連装砲x1 \n★max\t4+12.7cm連装砲x3\t⇒12.7cm連装砲C型改二", Days = new string[] {"月","火","水"}, ShipName = "夕立改二"},
            new IATable { Equip = "12.7cm連装砲B型改二", Info = "★0~5\n★6~9\t2/4+12.7cm連装砲x1 \n★max\t4+12.7cm連装砲x3\t⇒12.7cm連装砲C型改二", Days = new string[] {"月","火","水","木"}, ShipName = "江風改二"},
            new IATable { Equip = "12.7cm連装砲C型改二", Info = "★0~5\t2+12.7cm連装砲x1 /3+12.7cm連装砲x1 /4+22号対水上電探x2+新型砲熕兵装資材x1 +戦闘詳報x1\t⇒12.7cm連装砲D型改二", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "満潮改二"},
            new IATable { Equip = "12.7cm連装砲C型改二", Info = "★0~5\t2+12.7cm連装砲x1 /3+12.7cm連装砲x1 /4+22号対水上電探x2+新型砲熕兵装資材x1 +戦闘詳報x1\t⇒12.7cm連装砲D型改二", Days = new string[] {"水","木","金","土"}, ShipName = "荒潮改二"},
            new IATable { Equip = "12.7cm連装砲C型改二", Info = "★0~5\t2+12.7cm連装砲x1 /3+12.7cm連装砲x1 /4+22号対水上電探x2+新型砲熕兵装資材x1 +戦闘詳報x1\t⇒12.7cm連装砲D型改二", Days = new string[] {"木","金","土"}, ShipName = "雪風改"},
            new IATable { Equip = "12.7cm連装砲D型改二", Info = "★0~5\t5+10cm連装高角砲x2/6+10cm連装高角砲x1 ", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "長波改二"},
            //中口径主砲
            new IATable { Equip = "14cm単装砲", Info = "★0~5\t1/1+14cm単装砲x1 /3+14cm単装砲x2\t⇒14cm連装砲", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = ""},
            new IATable { Equip = "14cm連装砲", Info = "★0~5\t1/2+14cm連装砲", Days = new string[] {"月","木"}, ShipName = "夕張"},
            new IATable { Equip = "15.2cm連装砲", Info = "★0~5\t2/2+15.2cm連装砲x1 /4+15.2cm連装砲x1\t⇒15.2cm連装砲改", Days = new string[] {"木","金","土"}, ShipName = "阿賀野"},
            new IATable { Equip = "15.2cm連装砲", Info = "★0~5\t2/2+15.2cm連装砲x1 /4+15.2cm連装砲x1\t⇒15.2cm連装砲改", Days = new string[] {"日","月","金","土"}, ShipName = "能代"},
            new IATable { Equip = "15.2cm連装砲", Info = "★0~5\t2/2+15.2cm連装砲x1 /4+15.2cm連装砲x1\t⇒15.2cm連装砲改", Days = new string[] {"月","火","水","木"}, ShipName = "矢矧"},
            new IATable { Equip = "15.2cm連装砲改", Info = "★0~5\t2+15.2cm連装砲x1 /3+15.2cm連装砲x1 ", Days = new string[] {"水","木","金","土"}, ShipName = "矢矧"},
            new IATable { Equip = "15.2cm連装砲改", Info = "★0~5\t2+15.2cm連装砲x1 /3+15.2cm連装砲x1 ", Days = new string[] {"日","月","火","土"}, ShipName = "酒匂"},
            new IATable { Equip = "15.5cm三連装砲", Info = "★0~5\t2/2+15.5cm三連装砲x1 /4+15.5cm三連装砲x2+新型砲熕兵装資材x1\t⇒15.5cm三連装砲改(大淀)", Days = new string[] {"金","土"}, ShipName = "最上"},
            new IATable { Equip = "15.5cm三連装砲", Info = "★0~5\t2/2+15.5cm三連装砲x1 /4+15.5cm三連装砲x2+新型砲熕兵装資材x1\t⇒15.5cm三連装砲改(大淀)", Days = new string[] {"日","月","金","土"}, ShipName = "大淀"},
            new IATable { Equip = "15.5cm三連装砲改", Info = "★0~5\t4+15.5cm三連装砲x2/5+15.5cm三連装副砲x2/2+15.5cm三連装副砲x1\t⇒15.5cm三連装副砲改★+7", Days = new string[] {"日","金","土"}, ShipName = "大淀改"},
            new IATable { Equip = "20.3cm連装砲", Info = "★0~5\t2/2+20.3cm連装砲x1 /4+20.3cm連装砲x2\t⇒20.3cm(2号)連装砲", Days = new string[] {"日","木","金","土"}, ShipName = "青葉"},
            new IATable { Equip = "20.3cm連装砲", Info = "★0~5\t2/2+20.3cm連装砲x1 /4+20.3cm連装砲x2\t⇒20.3cm(2号)連装砲", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "衣笠"},
            new IATable { Equip = "20.3cm(2号)連装砲", Info = "★0~5\t2/2+20.3cm(2号)連装砲x1 /4+20.3cm(2号)連装砲x1\t⇒20.3cm(3号)連装砲", Days = new string[] {"日","月","火"}, ShipName = "妙高"},
            new IATable { Equip = "20.3cm(3号)連装砲", Info = "★0~5\t2/3+20.3cm(3号)連装砲x1 ", Days = new string[] {"火","水"}, ShipName = "三隈"},
            new IATable { Equip = "203mm/53 連装砲", Info = "★0~5\t3+20.3cm連装砲x2/4+20.3cm(2号)連装砲x1 ", Days = new string[] {"日","月","火","水"}, ShipName = "Zara due"},
            //大口径主砲
            new IATable { Equip = "35.6cm連装砲", Info = "★0~5\t1/2+35.6cm連装砲x1 /5+35.6cm連装砲x3\t⇒試製35.6cm三連装砲", Days = new string[] {"日","金","土"}, ShipName = "扶桑"},
            new IATable { Equip = "35.6cm連装砲(ダズル迷彩)", Info = "★0~5\t2+35.6cm連装砲x1 /3+35.6cm連装砲x2", Days = new string[] {"日","月","火","水","土"}, ShipName = "榛名改二"},
            new IATable { Equip = "試製35.6cm三連装砲", Info = "★0~5\t3+35.6cm連装砲x2/4+35.6cm連装砲x3", Days = new string[] {"水","木"}, ShipName = "金剛改二"},
            new IATable { Equip = "試製35.6cm三連装砲", Info = "★0~5\t3+35.6cm連装砲x2/4+35.6cm連装砲x3", Days = new string[] {"木","金"}, ShipName = "榛名改二"},
            new IATable { Equip = "試製35.6cm三連装砲", Info = "★0~5\t3+35.6cm連装砲x2/4+35.6cm連装砲x3", Days = new string[] {"水","木","金","土"}, ShipName = "扶桑改二"},
            new IATable { Equip = "試製35.6cm三連装砲", Info = "★0~5\t3+35.6cm連装砲x2/4+35.6cm連装砲x3", Days = new string[] {"日","木","金","土"}, ShipName = "山城改二"},
            new IATable { Equip = "38cm連装砲", Info = "★0~5\t2+35.6cm連装砲x1 /3+35.6cm連装砲x2/6+41cm連装砲x2\t⇒38cm連装砲改★+3", Days = new string[] {"木","金","土"}, ShipName = "Bismarck"},
            new IATable { Equip = "38cm連装砲改", Info = "★0~5\t3+41cm連装砲x1 /4+41cm連装砲x2", Days = new string[] {"日","月","火"}, ShipName = "Bismarck"},
            new IATable { Equip = "38.1cm Mk.I連装砲", Info = "★0~5\t3+35.6cm連装砲x2/3+41cm連装砲x2/6+25mm単装機銃x2\t⇒38.1cm Mk.I/N連装砲改", Days = new string[] {"日","木","金","土"}, ShipName = "Warspite"},
            new IATable { Equip = "38.1cm Mk.I/N連装砲改", Info = "★0~5\t3+41cm連装砲x1 /4+41cm連装砲x2", Days = new string[] {"火","水","木","金"}, ShipName = "Warspite"},
            new IATable { Equip = "381mm/50 三連装砲", Info = "★0~5\t2+35.6cm連装砲x1 /3+35.6cm連装砲x2/7+25mm連装機銃x2\t⇒381mm/50 三連装砲改★+3", Days = new string[] {"火","水","木","金"}, ShipName = "Littorio"},
            new IATable { Equip = "381mm/50 三連装砲", Info = "★0~5\t2+35.6cm連装砲x1 /3+35.6cm連装砲x2/7+25mm連装機銃x2\t⇒381mm/50 三連装砲改★+3", Days = new string[] {"日","月","土"}, ShipName = "Roma"},
            new IATable { Equip = "381mm/50 三連装砲改", Info = "★0~5\t3+41cm連装砲x1 /4+41cm連装砲x2", Days = new string[] {"日","月","土"}, ShipName = "Littorio"},
            new IATable { Equip = "381mm/50 三連装砲改", Info = "★0~5\t3+41cm連装砲x1 /4+41cm連装砲x2", Days = new string[] {"火","水","木","金"}, ShipName = "Roma"},
            new IATable { Equip = "41cm連装砲", Info = "★0~5\t2+41cm連装砲x1 /3+41cm連装砲x2/10+46cm三連装砲x2+新型砲熕兵装資材x2\t⇒試製41cm三連装砲", Days = new string[] {"火","金","土"}, ShipName = "長門"},
            new IATable { Equip = "41cm連装砲", Info = "★0~5\t2+41cm連装砲x1 /3+41cm連装砲x2/10+46cm三連装砲x2+新型砲熕兵装資材x2\t⇒試製41cm三連装砲", Days = new string[] {"日","月","木"}, ShipName = "陸奥"},
            new IATable { Equip = "試製41cm三連装砲", Info = "★0~5\t4+41cm連装砲x2/5+41cm連装砲x3/12+46cm三連装砲x2+新型砲熕兵装資材x2\t⇒41cm三連装砲改", Days = new string[] {"日","月","水","木"}, ShipName = "長門改"},
            new IATable { Equip = "試製41cm三連装砲", Info = "★0~5\t4+41cm連装砲x2/5+41cm連装砲x3/12+46cm三連装砲x2+新型砲熕兵装資材x2\t⇒41cm三連装砲改", Days = new string[] {"火","水","金","土"}, ShipName = "陸奥改"},
            new IATable { Equip = "41cm三連装砲改", Info = "★0~5\t6+41cm連装砲x2/7+46cm三連装砲x2", Days = new string[] {"月","火","水"}, ShipName = "長門改二"},
            new IATable { Equip = "16inch三連装砲 Mk.7", Info = "★0~5\t6+41cm連装砲x3/8+46cm三連装砲x3/12+32号対水上電探x2\t⇒16inch三連装砲 Mk.7+GFCS", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "Iowa"},
            new IATable { Equip = "16inch三連装砲 Mk.7+GFCS", Info = "★0~5\t8+22号対水上電探x2/8+32号対水上電探x2", Days = new string[] {"日","木","金","土"}, ShipName = "Iowa"},
            new IATable { Equip = "試製46cm連装砲", Info = "★0~5\t3+41cm連装砲x2/4+41cm連装砲x3/8+41cm連装砲(4)\t⇒46cm三連装砲★+5", Days = new string[] {"日","月"}, ShipName = "大和"},
            new IATable { Equip = "試製46cm連装砲", Info = "★0~5\t3+41cm連装砲x2/4+41cm連装砲x3/8+41cm連装砲(4)\t⇒46cm三連装砲★+5", Days = new string[] {"火","水"}, ShipName = "武蔵"},
            new IATable { Equip = "46cm三連装砲", Info = "★0~5\t4+46cm三連装砲x1 /5+46cm三連装砲x2", Days = new string[] {"火","水","木","金","土"}, ShipName = "大和"},
            new IATable { Equip = "46cm三連装砲", Info = "★0~5\t4+46cm三連装砲x1 /5+46cm三連装砲x2", Days = new string[] {"火","水","木"}, ShipName = "大和改"},
            new IATable { Equip = "46cm三連装砲", Info = "★0~5\t4+46cm三連装砲x1 /5+46cm三連装砲x2", Days = new string[] {"日","月"}, ShipName = "武蔵"},
            new IATable { Equip = "試製51cm連装砲", Info = "★0~5\t5+46cm三連装砲x2/7+46cm三連装砲x3", Days = new string[] {"月","火"}, ShipName = "大和改"},
            new IATable { Equip = "試製51cm連装砲", Info = "★0~5\t5+46cm三連装砲x2/7+46cm三連装砲x3", Days = new string[] {"月","水"}, ShipName = "武蔵改"},
            //副砲
            new IATable { Equip = "90mm単装高角砲", Info = "★0~5\t1+10cm連装高角砲x1 /1+10cm連装高角砲x2", Days = new string[] {"月","火","水","木"}, ShipName = "Littorio"},
            new IATable { Equip = "90mm単装高角砲", Info = "★0~5\t1+10cm連装高角砲x1 /1+10cm連装高角砲x2", Days = new string[] {"日","木","金","土"}, ShipName = "Roma"},
            new IATable { Equip = "15.2cm単装砲", Info = "★0~5\t1/2+15.2cm単装砲x1 /3+15.2cm単装砲x2\t⇒15.2cm連装砲", Days = new string[] {"日","月","土"}, ShipName = "金剛"},
            new IATable { Equip = "15.2cm単装砲", Info = "★0~5\t1/2+15.2cm単装砲x1 /3+15.2cm単装砲x2\t⇒15.2cm連装砲", Days = new string[] {"月","火","水"}, ShipName = "山城"},
            new IATable { Equip = "15.2cm単装砲", Info = "★0~5\t1/2+15.2cm単装砲x1 /3+15.2cm単装砲x2\t⇒15.2cm連装砲", Days = new string[] {"日","月","火"}, ShipName = "阿賀野"},
            new IATable { Equip = "15.5cm三連装副砲", Info = "★0~5\t2/2+15.5cm三連装副砲x1 /4+15.5cm三連装副砲x2+新型砲熕兵装資材x1\t⇒15.5cm三連装副砲改", Days = new string[] {"金","土"}, ShipName = "大和"},
            new IATable { Equip = "15.5cm三連装副砲", Info = "★0~5\t2/2+15.5cm三連装副砲x1 /4+15.5cm三連装副砲x2+新型砲熕兵装資材x1\t⇒15.5cm三連装副砲改", Days = new string[] {"金","土"}, ShipName = "武蔵改"},
            new IATable { Equip = "15.5cm三連装副砲", Info = "★0~5\t2/2+15.5cm三連装副砲x1 /4+15.5cm三連装副砲x2+新型砲熕兵装資材x1\t⇒15.5cm三連装副砲改", Days = new string[] {"日","金","土"}, ShipName = "武蔵"},
            new IATable { Equip = "15.5cm三連装副砲改", Info = "★0~5\t4+15.5cm三連装副砲x2/5+15.5cm三連装砲x2/2+15.5cm三連装砲x1\t⇒15.5cm三連装砲改★+7", Days = new string[] {"金","土"}, ShipName = "大和改"},
            new IATable { Equip = "15.5cm三連装副砲改", Info = "★0~5\t4+15.5cm三連装副砲x2/5+15.5cm三連装砲x2/2+15.5cm三連装砲x1\t⇒15.5cm三連装砲改★+7", Days = new string[] {"日","月"}, ShipName = "武蔵改"},
            new IATable { Equip = "OTO 152mm三連装速射砲", Info = "★0~5\t2/3+15.5cm三連装砲x1 ", Days = new string[] {"日","火","水","土"}, ShipName = "Littorio"},
            new IATable { Equip = "OTO 152mm三連装速射砲", Info = "★0~5\t2/3+15.5cm三連装砲x1 ", Days = new string[] {"日","月","木","金"}, ShipName = "Roma"},
            new IATable { Equip = "15.2cm三連装砲", Info = "★0~5\t6+15.5cm三連装副砲x1 /7+22号対水上電探x2", Days = new string[] {"月","火","水","木"}, ShipName = "Richelieu"},
            new IATable { Equip = "12.7cm連装高角砲", Info = "★0~5\t2+12.7cm連装高角砲x1 /3+12.7cm連装高角砲x1 /6+10cm連装高角砲x1\t⇒8cm高角砲", Days = new string[] {"金","土"}, ShipName = "摩耶改二"},
            new IATable { Equip = "12.7cm連装高角砲", Info = "★0~5\t2+12.7cm連装高角砲x1 /3+12.7cm連装高角砲x1 /6+10cm連装高角砲x1\t⇒8cm高角砲", Days = new string[] {"日","金","土"}, ShipName = "鈴谷"},
            new IATable { Equip = "12.7cm連装高角砲", Info = "★0~5\t2+12.7cm連装高角砲x1 /3+12.7cm連装高角砲x1 /6+10cm連装高角砲x1\t⇒8cm高角砲", Days = new string[] {"日","月","土"}, ShipName = "熊野"},
            new IATable { Equip = "8cm高角砲", Info = "★0~5\t3+10cm連装高角砲x1 /4+10cm連装高角砲x2/8+25mm単装機銃x2\t⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"火","水","木"}, ShipName = "鈴谷改二"},
            new IATable { Equip = "8cm高角砲", Info = "★0~5\t3+10cm連装高角砲x1 /4+10cm連装高角砲x2/8+25mm単装機銃x2\t⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"月","火","水"}, ShipName = "熊野改二"},
            new IATable { Equip = "8cm高角砲", Info = "★0~5\t3+10cm連装高角砲x1 /4+10cm連装高角砲x2/8+25mm単装機銃x2\t⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"日","木","金","土"}, ShipName = "阿賀野"},
            new IATable { Equip = "8cm高角砲", Info = "★0~5\t3+10cm連装高角砲x1 /4+10cm連装高角砲x2/8+25mm単装機銃x2\t⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"日","月","金","土"}, ShipName = "能代"},
            new IATable { Equip = "8cm高角砲", Info = "★0~5\t3+10cm連装高角砲x1 /4+10cm連装高角砲x2/8+25mm単装機銃x2\t⇒8cm高角砲改+増設機銃(矢矧/鈴谷改二/熊野改二)", Days = new string[] {"日","月","火"}, ShipName = "矢矧"},
            new IATable { Equip = "8cm高角砲改+増設機銃", Info = "★0~5\t4+10cm連装高角砲x2/6+25mm単装機銃x2", Days = new string[] {"火","水","木"}, ShipName = "鈴谷改二"},
            new IATable { Equip = "8cm高角砲改+増設機銃", Info = "★0~5\t4+10cm連装高角砲x2/6+25mm単装機銃x2", Days = new string[] {"火","水","木"}, ShipName = "矢矧"},
            new IATable { Equip = "8cm高角砲改+増設機銃", Info = "★0~5\t4+10cm連装高角砲x2/6+25mm単装機銃x2", Days = new string[] {"火","水","木"}, ShipName = "酒匂"},
            new IATable { Equip = "8cm高角砲改+増設機銃", Info = "★0~5\t4+10cm連装高角砲x2/6+25mm単装機銃x2", Days = new string[] {"月","火","水"}, ShipName = "熊野改二"},
            //魚雷
            new IATable { Equip = "61cm三連装魚雷", Info = "★0~5\t1/1+61cm三連装魚雷x1 /2+61cm三連装魚雷x2\t⇒61cm三連装(酸素)魚雷", Days = new string[] {"木","金","土" }, ShipName = "吹雪"},
            new IATable { Equip = "61cm三連装魚雷", Info = "★0~5\t1/1+61cm三連装魚雷x1 /2+61cm三連装魚雷x2\t⇒61cm三連装(酸素)魚雷", Days = new string[] {"日","月","火"}, ShipName = "叢雲"},
            new IATable { Equip = "61cm三連装(酸素)魚雷", Info = "★0~5\t1/1+61cm三連装魚雷x1 /3+61cm四連装魚雷x2\t⇒61cm四連装(酸素)魚雷★+5", Days = new string[] {"木","金","土"}, ShipName = "吹雪改二"},
            new IATable { Equip = "61cm四連装魚雷", Info = "★0~5\t1/1+61cm四連装魚雷x1 /3+61cm四連装魚雷x2\t⇒61cm四連装(酸素)魚雷★+3", Days = new string[] {"日","月","火","金","土"}, ShipName = ""},
            new IATable { Equip = "61cm四連装(酸素)魚雷", Info = "★0~5\t1/2+61cm四連装(酸素)魚雷x1 /5+61cm四連装(酸素)魚雷x3\t⇒61cm五連装(酸素)魚雷", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "大井"},
            new IATable { Equip = "61cm四連装(酸素)魚雷", Info = "★0~5\t1/2+61cm四連装(酸素)魚雷x1 /5+61cm四連装(酸素)魚雷x3\t⇒61cm五連装(酸素)魚雷", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "北上"},
            new IATable { Equip = "61cm五連装(酸素)魚雷", Info = "★0~5\t3/3+61cm五連装(酸素)魚雷x1 ", Days = new string[] {"水","木"}, ShipName = "島風"},
            new IATable { Equip = "試製61cm六連装(酸素)魚雷", Info = "★0~5\t5+61cm四連装(酸素)魚雷x2/6+61cm五連装(酸素)魚雷x1 ", Days = new string[] {"水","木","金","土"}, ShipName = "初月"},
            new IATable { Equip = "試製61cm六連装(酸素)魚雷", Info = "★0~5\t5+61cm四連装(酸素)魚雷x2/6+61cm五連装(酸素)魚雷x1 ", Days = new string[] {"日","土"}, ShipName = "島風"},
            //艦上戦闘機
            new IATable { Equip = "九六式艦戦", Info = "★0~5\t1+九六式艦戦x1 /1+7.7mm機銃x1 /2+九六式艦戦x2\t⇒零式艦戦21型★+3", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "鳳翔"},
            new IATable { Equip = "零式艦戦21型", Info = "★0~5\t2+零式艦戦21型x1 /2+零式艦戦21型x2/3+7.7mm機銃x2\t⇒零式艦戦32型★+3", Days = new string[] {"木","金","土"}, ShipName = "赤城"},
            new IATable { Equip = "零式艦戦21型", Info = "★0~5\t2+零式艦戦21型x1 /2+零式艦戦21型x2/3+7.7mm機銃x2\t⇒零式艦戦32型★+3", Days = new string[] {"日","月","火"}, ShipName = "加賀"},
            new IATable { Equip = "零式艦戦21型(熟練)", Info = "★0~5\t2+零式艦戦21型x2/2+零式艦戦21型x3/3+7.7mm機銃x3\t⇒零式艦戦32型(熟練)★+3", Days = new string[] {"木","金","土"}, ShipName = "赤城"},
            new IATable { Equip = "零式艦戦21型(熟練)", Info = "★0~5\t2+零式艦戦21型x2/2+零式艦戦21型x3/3+7.7mm機銃x3\t⇒零式艦戦32型(熟練)★+3", Days = new string[] {"日","月","火"}, ShipName = "加賀"},
            new IATable { Equip = "零式艦戦32型", Info = "★0~5\t2+零式艦戦21型x1 /3+零式艦戦21型x2/4+零式艦戦32型x1\t⇒零式艦戦52型★+3", Days = new string[] {"日","月"}, ShipName = "赤城"},
            new IATable { Equip = "零式艦戦32型", Info = "★0~5\t2+零式艦戦21型x1 /3+零式艦戦21型x2/4+零式艦戦32型x1\t⇒零式艦戦52型★+3", Days = new string[] {"水","木"}, ShipName = "加賀"},
            new IATable { Equip = "零式艦戦32型(熟練)", Info = "★0~5\t2+零式艦戦21型x2/3+零式艦戦21型x3/4+零式艦戦32型x2\t⇒零式艦戦52型(熟練)★+3", Days = new string[] {"日","月"}, ShipName = "赤城"},
            new IATable { Equip = "零式艦戦32型(熟練)", Info = "★0~5\t2+零式艦戦21型x2/3+零式艦戦21型x3/4+零式艦戦32型x2\t⇒零式艦戦52型(熟練)★+3", Days = new string[] {"水","木"}, ShipName = "加賀"},
            new IATable { Equip = "零式艦戦52型", Info = "★0~5\t3+零式艦戦52型x1 /3+零式艦戦52型x2", Days = new string[] {"木","金","土"}, ShipName = "翔鶴"},
            new IATable { Equip = "零式艦戦52型", Info = "★0~5\t3+零式艦戦52型x1 /3+零式艦戦52型x2", Days = new string[] {"日","月","水"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零式艦戦52型(熟練)", Info = "★0~5\t3+零式艦戦52型x2/4+零式艦戦52型x3", Days = new string[] {"木","金","土"}, ShipName = "翔鶴"},
            new IATable { Equip = "零式艦戦52型(熟練)", Info = "★0~5\t3+零式艦戦52型x2/4+零式艦戦52型x3", Days = new string[] {"日","月","水"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零戦52型丙(六〇一空)", Info = "★0~5\t3+零式艦戦52型x2/4+天山x2", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "大鳳"},
            new IATable { Equip = "零戦52型丙(六〇一空)", Info = "★0~5\t3+零式艦戦52型x2/4+天山x2", Days = new string[] {"水","木","金","土"}, ShipName = "雲龍"},
            new IATable { Equip = "零戦52型丙(付岩井小隊)", Info = "★0~5\t3+零式艦戦52型x2/4+零式艦戦52型x3", Days = new string[] {"火","木"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零戦52型甲(付岩本小隊)", Info = "★0~5\t3+零式艦戦52型x2/4+零式艦戦52型x3", Days = new string[] {"金","土"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零式艦戦53型(岩本隊)", Info = "★0~5\t3+零式艦戦52型x2/4+零式艦戦52型x3", Days = new string[] {"金","土"}, ShipName = "瑞鶴"},
            new IATable { Equip = "F4F-3", Info = "★0~5\t2/2+九六式艦戦x1 /3+12.7mm単装機銃x2\t⇒F4F-4", Days = new string[] {"日","水","木","金","土"}, ShipName = "Saratoga"},
            new IATable { Equip = "F4F-3", Info = "★0~5\t2/2+九六式艦戦x1 /3+12.7mm単装機銃x2\t⇒F4F-4", Days = new string[] {"金","土"}, ShipName = "Saratoga改"},
            new IATable { Equip = "F4F-3", Info = "★0~5\t2/2+九六式艦戦x1 /3+12.7mm単装機銃x2\t⇒F4F-4", Days = new string[] {"火","水"}, ShipName = "Saratoga MK.II"},
            new IATable { Equip = "F4F-4", Info = "★0~5\t3+零式艦戦21型x1 /3+零式艦戦32型x1 /6+零式艦戦52型x2\t⇒F6F-3", Days = new string[] {"月","火"}, ShipName = "Saratoga"},
            new IATable { Equip = "F4F-4", Info = "★0~5\t3+零式艦戦21型x1 /3+零式艦戦32型x1 /6+零式艦戦52型x2\t⇒F6F-3", Days = new string[] {"月","火","水"}, ShipName = "Saratoga改"},
            new IATable { Equip = "F4F-4", Info = "★0~5\t3+零式艦戦21型x1 /3+零式艦戦32型x1 /6+零式艦戦52型x2\t⇒F6F-3", Days = new string[] {"月","木"}, ShipName = "Saratoga MK.II"},
            new IATable { Equip = "F6F-3", Info = "★0~5\t4+零式艦戦52型x2/6+紫電改二x1 /8+紫電改二x2\t⇒F6F-5", Days = new string[] {"火","水","木"}, ShipName = "Saratoga改"},
            new IATable { Equip = "F6F-3", Info = "★0~5\t4+零式艦戦52型x2/6+紫電改二x1 /8+紫電改二x2\t⇒F6F-5", Days = new string[] {"火","水","木"}, ShipName = "Saratoga MK.II"},
            new IATable { Equip = "F6F-5", Info = "★0~5\t6+紫電改二x2/8+烈風x1 ", Days = new string[] {"火","水","木"}, ShipName = "Saratoga MK.II"},
            //艦上爆撃機
            new IATable { Equip = "零式艦戦62型(爆戦)", Info = "★0~5\t3+零式艦戦52型x2/4+彗星x2/6+烈風x1\t⇒零式艦戦63型(爆戦)(鈴谷航改二)", Days = new string[] {"日","月"}, ShipName = "翔鶴"},
            new IATable { Equip = "零式艦戦62型(爆戦)", Info = "★0~5\t3+零式艦戦52型x2/4+彗星x2/6+烈風x1\t⇒零式艦戦63型(爆戦)(鈴谷航改二)", Days = new string[] {"日","月"}, ShipName = "鈴谷航改二"},
            new IATable { Equip = "零式艦戦62型(爆戦)", Info = "★0~5\t3+零式艦戦52型x2/4+彗星x2/6+烈風x1\t⇒零式艦戦63型(爆戦)(鈴谷航改二)", Days = new string[] {"日","金","土"}, ShipName = "隼鷹"},
            new IATable { Equip = "零戦62型(爆戦/岩井隊)", Info = "★0~5\t3+零式艦戦52型x2/4+彗星x2", Days = new string[] {"火","木"}, ShipName = "瑞鶴"},
            new IATable { Equip = "零式艦戦63型(爆戦)", Info = "★0~5\t4+零式艦戦52型x3/5+烈風x1 ", Days = new string[] {"月","火","水","木"}, ShipName = "鈴谷航改二"},
            new IATable { Equip = "零式艦戦63型(爆戦)", Info = "★0~5\t4+零式艦戦52型x3/5+烈風x1 ", Days = new string[] {"火","水","木","金"}, ShipName = "熊野航改二"},
            //艦上攻撃機

            //艦上偵察機
            new IATable { Equip = "試製景雲(艦偵型)", Info = "★0~5\t6+流星x1 /7+烈風x1 /10+ネ式エンジンx1\t⇒噴式景雲改", Days = new string[] {"日","金","土"}, ShipName = "翔鶴改二甲"},
            new IATable { Equip = "試製景雲(艦偵型)", Info = "★0~5\t6+流星x1 /7+烈風x1 /10+ネ式エンジンx1\t⇒噴式景雲改", Days = new string[] {"日","月","火"}, ShipName = "瑞鶴改二甲"},
            //水上偵察機
            new IATable { Equip = "零式水上偵察機", Info = "★0~5\t2+零式水上偵察機x1 /3+零式水上偵察機x2/5+零式艦戦21型x3\t⇒二式水戦改", Days = new string[] {"金","土"}, ShipName = "千歳甲"},
            new IATable { Equip = "零式水上偵察機", Info = "★0~5\t2+零式水上偵察機x1 /3+零式水上偵察機x2/5+零式艦戦21型x3\t⇒二式水戦改", Days = new string[] {"水","木"}, ShipName = "千代田甲"},
            new IATable { Equip = "零式水上偵察機", Info = "★0~5\t2+零式水上偵察機x1 /3+零式水上偵察機x2/5+零式艦戦21型x3\t⇒二式水戦改", Days = new string[] {"日","木","金","土"}, ShipName = "秋津洲改"},
            new IATable { Equip = "零式水上偵察機", Info = "★0~5\t2+零式水上偵察機x1 /3+零式水上偵察機x2/5+零式艦戦21型x3\t⇒二式水戦改", Days = new string[] {"月","火","水"}, ShipName = "瑞穂"},
            new IATable { Equip = "零式水上観測機", Info = "★0~5\t3+瑞雲x1 /4+零式水上観測機x1 ", Days = new string[] {"木","金","土"}, ShipName = "武蔵"},
            new IATable { Equip = "零式水上観測機", Info = "★0~5\t3+瑞雲x1 /4+零式水上観測機x1 ", Days = new string[] {"月","火","水"}, ShipName = "瑞穂"},
            new IATable { Equip = "九八式水上偵察機(夜偵)", Info = "★0~5\t3+零式水上偵察機x1 /4+零式水上偵察機x2", Days = new string[] {"日","月","木","金","土"}, ShipName = "川内改二"},
            //水上爆撃機
            new IATable { Equip = "Ro.43水偵", Info = "★0~5\t1+零式水上偵察機x1 /2+瑞雲x1 /3+零式水上偵察機x2\t⇒Ro.44水上戦闘機", Days = new string[] {"日","土"}, ShipName = "Italia"},
            new IATable { Equip = "Ro.43水偵", Info = "★0~5\t1+零式水上偵察機x1 /2+瑞雲x1 /3+零式水上偵察機x2\t⇒Ro.44水上戦闘機", Days = new string[] {"火","水"}, ShipName = "Roma改"},
            new IATable { Equip = "Ro.43水偵", Info = "★0~5\t1+零式水上偵察機x1 /2+瑞雲x1 /3+零式水上偵察機x2\t⇒Ro.44水上戦闘機", Days = new string[] {"月","火","水","木","金"}, ShipName = "Zara改"},
            new IATable { Equip = "Ro.43水偵", Info = "★0~5\t1+零式水上偵察機x1 /2+瑞雲x1 /3+零式水上偵察機x2\t⇒Ro.44水上戦闘機", Days = new string[] {"木","金","土"}, ShipName = "Zara due"},
            //水上戦闘機
            new IATable { Equip = "二式水戦改", Info = "★0~5\t5+零式艦戦21型x2/7+零式水上偵察機x2/9+瑞雲x2\t⇒強風改", Days = new string[] {"日","金","土"}, ShipName = "瑞穂"},
            new IATable { Equip = "二式水戦改(熟練)", Info = "★0~5\t7+零式艦戦32型x2/8+瑞雲x3", Days = new string[] {"日","金","土"}, ShipName = "瑞穂"},
            new IATable { Equip = "強風改", Info = "★0~5\t6+紫電改二x1 /7+紫電改二x1 ", Days = new string[] {"火","水","木"}, ShipName = "瑞穂"},
            new IATable { Equip = "強風改", Info = "★0~5\t6+紫電改二x1 /7+紫電改二x1 ", Days = new string[] {"月","火","水","木"}, ShipName = "鈴谷改二"},
            new IATable { Equip = "Ro.44水上戦闘機", Info = "★0~5\t3+瑞雲x1 /5+瑞雲x2/8+Ro.44水上戦闘機x1\t⇒Ro.44水上戦闘機bis", Days = new string[] {"日","木","金","土"}, ShipName = "Zara due"},
            new IATable { Equip = "Ro.44水上戦闘機bis", Info = "★0~5\t4+瑞雲x2/6+Ro.44水上戦闘機x1 ", Days = new string[] {"金","土"}, ShipName = "Zara due"},
            new IATable { Equip = "瑞雲", Info = "★0~5\t3+瑞雲x1 /5+瑞雲x1 /7+瑞雲x2+熟練搭乗員x1\t⇒瑞雲(六三四空)", Days = new string[] {"日","金","土"}, ShipName = "伊勢改"},
            new IATable { Equip = "瑞雲", Info = "★0~5\t3+瑞雲x1 /5+瑞雲x1 /7+瑞雲x2+熟練搭乗員x1\t⇒瑞雲(六三四空)", Days = new string[] {"日","金","土"}, ShipName = "日向改"},
            new IATable { Equip = "瑞雲", Info = "★0~5\t3+瑞雲x1 /5+瑞雲x1 /7+瑞雲x2+熟練搭乗員x1\t⇒瑞雲(六三四空)", Days = new string[] {"月","火","水","木"}, ShipName = "最上改"},
            new IATable { Equip = "瑞雲(六三四空)", Info = "★0~5\t5+瑞雲x1 /6+瑞雲x2", Days = new string[] {"日","金","土"}, ShipName = "伊勢改"},
            new IATable { Equip = "瑞雲(六三四空)", Info = "★0~5\t5+瑞雲x1 /6+瑞雲x2", Days = new string[] {"日","金","土"}, ShipName = "日向改"},
            new IATable { Equip = "瑞雲(六三四空/熟練)", Info = "★0~5\t6+瑞雲x2/7+瑞雲x3", Days = new string[] {"日","金","土"}, ShipName = "日向改"},
            //電探
            new IATable { Equip = "13号対空電探", Info = "★0~5\t2/3+13号対空電探x1 /5+21号対空電探x1\t⇒13号対空電探改", Days = new string[] {"日","月","金","土"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "13号対空電探", Info = "★0~5\t2/3+13号対空電探x1 /5+21号対空電探x1\t⇒13号対空電探改", Days = new string[] {"日","木","金","土"}, ShipName = "時雨改二"},
            new IATable { Equip = "13号対空電探", Info = "★0~5\t2/3+13号対空電探x1 /5+21号対空電探x1\t⇒13号対空電探改", Days = new string[] {"火","水","木"}, ShipName = "秋月"},
            new IATable { Equip = "13号対空電探", Info = "★0~5\t2/3+13号対空電探x1 /5+21号対空電探x1\t⇒13号対空電探改", Days = new string[] {"月","火","水"}, ShipName = "照月"},
            new IATable { Equip = "13号対空電探改", Info = "★0~5\t3+13号対空電探x1 /4+13号対空電探x2", Days = new string[] {"日","金","土"}, ShipName = "初霜改二"},
            new IATable { Equip = "13号対空電探改", Info = "★0~5\t3+13号対空電探x1 /4+13号対空電探x2", Days = new string[] {"日","月","火","水"}, ShipName = "雪風"},
            new IATable { Equip = "13号対空電探改", Info = "★0~5\t3+13号対空電探x1 /4+13号対空電探x2", Days = new string[] {"木","金","土"}, ShipName = "磯風改"},
            new IATable { Equip = "22号対水上電探", Info = "★0~5\t2+22号対水上電探x1 /3+22号対水上電探x2/8+22号対水上電探x3\t⇒22号対水上電探改四", Days = new string[] {"日","月","金","土"}, ShipName = "日向"},
            new IATable { Equip = "22号対水上電探", Info = "★0~5\t2+22号対水上電探x1 /3+22号対水上電探x2/8+22号対水上電探x3\t⇒22号対水上電探改四", Days = new string[] {"月"}, ShipName = "日向改"},
            new IATable { Equip = "22号対水上電探", Info = "★0~5\t2+22号対水上電探x1 /3+22号対水上電探x2/8+22号対水上電探x3\t⇒22号対水上電探改四", Days = new string[] {"月","火","金","土"}, ShipName = "夕雲"},
            new IATable { Equip = "22号対水上電探", Info = "★0~5\t2+22号対水上電探x1 /3+22号対水上電探x2/8+22号対水上電探x3\t⇒22号対水上電探改四", Days = new string[] {"木","金","土"}, ShipName = "島風"},
            new IATable { Equip = "22号対水上電探改四", Info = "★0~5\t3+22号対水上電探x1 /4+22号対水上電探改四x1 ", Days = new string[] {"火","水","木","金"}, ShipName = "金剛改二"},
            new IATable { Equip = "22号対水上電探改四", Info = "★0~5\t3+22号対水上電探x1 /4+22号対水上電探改四x1 ", Days = new string[] {"日","木","金","土"}, ShipName = "妙高改二"},
            new IATable { Equip = "22号対水上電探改四", Info = "★0~5\t3+22号対水上電探x1 /4+22号対水上電探改四x1 ", Days = new string[] {"日","月","金","土"}, ShipName = "羽黒改二"},
            new IATable { Equip = "21号対空電探", Info = "★0~5\t2/3+21号対空電探x1 /5+21号対空電探x2\t⇒21号対空電探改", Days = new string[] {"日","月","金","土"}, ShipName = "伊勢"},
            new IATable { Equip = "21号対空電探", Info = "★0~5\t2/3+21号対空電探x1 /5+21号対空電探x2\t⇒21号対空電探改", Days = new string[] {"月"}, ShipName = "伊勢改"},
            new IATable { Equip = "21号対空電探", Info = "★0~5\t2/3+21号対空電探x1 /5+21号対空電探x2\t⇒21号対空電探改", Days = new string[] {"水","木","金","土"}, ShipName = "日向"},
            new IATable { Equip = "21号対空電探", Info = "★0~5\t2/3+21号対空電探x1 /5+21号対空電探x2\t⇒21号対空電探改", Days = new string[] {"水","木"}, ShipName = "日向改"},
            new IATable { Equip = "21号対空電探改", Info = "★0~5\t2+21号対空電探x1 /4+21号対空電探x2", Days = new string[] {"日","木"}, ShipName = "大和"},
            new IATable { Equip = "21号対空電探改", Info = "★0~5\t2+21号対空電探x1 /4+21号対空電探x2", Days = new string[] {"火","水","木"}, ShipName = "武蔵"},
            new IATable { Equip = "32号対水上電探", Info = "★0~5\t3+22号対水上電探x1 /4+22号対水上電探x2/10+32号対水上電探x1\t⇒32号対水上電探改", Days = new string[] {"水","木","金","土"}, ShipName = "伊勢"},
            new IATable { Equip = "32号対水上電探", Info = "★0~5\t3+22号対水上電探x1 /4+22号対水上電探x2/10+32号対水上電探x1\t⇒32号対水上電探改", Days = new string[] {"日","月","火"}, ShipName = "日向"},
            new IATable { Equip = "32号対水上電探", Info = "★0~5\t3+22号対水上電探x1 /4+22号対水上電探x2/10+32号対水上電探x1\t⇒32号対水上電探改", Days = new string[] {"月","火"}, ShipName = "日向改"},
            new IATable { Equip = "32号対水上電探改", Info = "★0~5\t5+22号対水上電探x3/7+32号対水上電探x1 ", Days = new string[] {"日","月","火"}, ShipName = "伊勢"},
            new IATable { Equip = "32号対水上電探改", Info = "★0~5\t5+22号対水上電探x3/7+32号対水上電探x1 ", Days = new string[] {"水","木","金","土"}, ShipName = "日向"},
            new IATable { Equip = "32号対水上電探改", Info = "★0~5\t5+22号対水上電探x3/7+32号対水上電探x1 ", Days = new string[] {"水","木"}, ShipName = "日向改"},
            //ソナー
            new IATable { Equip = "九三式水中聴音機", Info = "★0~5\t1/2+九三式水中聴音機x1 /3+九三式水中聴音機x2\t⇒三式水中探信儀★+3(五十鈴改二(月曜)/夕張)\n1/2+九三式水中聴音機x1 /6+三式水中探信儀x2\t⇒四式水中聴音機(五十鈴改二(木曜・金曜)/香取改/時雨改二)", Days = new string[] {"月","木","金"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "九三式水中聴音機", Info = "★0~5\t1/2+九三式水中聴音機x1 /3+九三式水中聴音機x2\t⇒三式水中探信儀★+3(五十鈴改二(月曜)/夕張)\n1/2+九三式水中聴音機x1 /6+三式水中探信儀x2\t⇒四式水中聴音機(五十鈴改二(木曜・金曜)/香取改/時雨改二)", Days = new string[] {"日","金","土"}, ShipName = "夕張"},
            new IATable { Equip = "九三式水中聴音機", Info = "★0~5\t1/2+九三式水中聴音機x1 /3+九三式水中聴音機x2\t⇒三式水中探信儀★+3(五十鈴改二(月曜)/夕張)\n1/2+九三式水中聴音機x1 /6+三式水中探信儀x2\t⇒四式水中聴音機(五十鈴改二(木曜・金曜)/香取改/時雨改二)", Days = new string[] {"日","金","土"}, ShipName = "香取改"},
            new IATable { Equip = "九三式水中聴音機", Info = "★0~5\t1/2+九三式水中聴音機x1 /3+九三式水中聴音機x2\t⇒三式水中探信儀★+3(五十鈴改二(月曜)/夕張)\n1/2+九三式水中聴音機x1 /6+三式水中探信儀x2\t⇒四式水中聴音機(五十鈴改二(木曜・金曜)/香取改/時雨改二)", Days = new string[] {"日","木","金","土"}, ShipName = "時雨改二"},
            new IATable { Equip = "三式水中探信儀", Info = "★0~5\t2/3+三式水中探信儀x1 ", Days = new string[] {"日","火","水"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "三式水中探信儀", Info = "★0~5\t2/3+三式水中探信儀x1 ", Days = new string[] {"火","水"}, ShipName = "夕張"},
            new IATable { Equip = "四式水中聴音機", Info = "★0~5\t3+九三式水中聴音機x2/4+四式水中聴音機x1 ", Days = new string[] {"木","金","土"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "四式水中聴音機", Info = "★0~5\t3+九三式水中聴音機x2/4+四式水中聴音機x1 ", Days = new string[] {"月","火"}, ShipName = "香取改"},
            new IATable { Equip = "四式水中聴音機", Info = "★0~5\t3+九三式水中聴音機x2/4+四式水中聴音機x1 ", Days = new string[] {"日"}, ShipName = "秋月"},
            new IATable { Equip = "四式水中聴音機", Info = "★0~5\t3+九三式水中聴音機x2/4+四式水中聴音機x1 ", Days = new string[] {"水"}, ShipName = "照月"},
            //爆雷
            new IATable { Equip = "九四式爆雷投射機", Info = "★0~5\t1/1+九四式爆雷投射機x1 /3+九四式爆雷投射機x2\t⇒三式爆雷投射機★+3", Days = new string[] {"水","木"}, ShipName = ""},
            new IATable { Equip = "三式爆雷投射機", Info = "★0~5\t2/2+三式爆雷投射機x1 ", Days = new string[] {"水","木"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "九五式爆雷", Info = "★0~5\t1/2+九五式爆雷x1 /3+九五式爆雷x2\t⇒二式爆雷", Days = new string[] {"火","水","木"}, ShipName = "那珂改二"},
            new IATable { Equip = "九五式爆雷", Info = "★0~5\t1/2+九五式爆雷x1 /3+九五式爆雷x2\t⇒二式爆雷", Days = new string[] {"日","木","金","土"}, ShipName = "神風"},
            new IATable { Equip = "九五式爆雷", Info = "★0~5\t1/2+九五式爆雷x1 /3+九五式爆雷x2\t⇒二式爆雷", Days = new string[] {"月","火","水","木"}, ShipName = "占守"},
            new IATable { Equip = "九五式爆雷", Info = "★0~5\t1/2+九五式爆雷x1 /3+九五式爆雷x2\t⇒二式爆雷", Days = new string[] {"水","木","金","土"}, ShipName = "択捉"},
            //対空強化弾

            //対艦強化弾
            new IATable { Equip = "九一式徹甲弾", Info = "★0~5\t1/1+九一式徹甲弾x1 /4+九一式徹甲弾x3\t⇒一式徹甲弾", Days = new string[] {"水","木","金","土"}, ShipName = "比叡"},
            new IATable { Equip = "九一式徹甲弾", Info = "★0~5\t1/1+九一式徹甲弾x1 /4+九一式徹甲弾x3\t⇒一式徹甲弾", Days = new string[] {"日","月","金","土"}, ShipName = "霧島"},
            new IATable { Equip = "一式徹甲弾", Info = "★0~5\t1+九一式徹甲弾x2/2+一式徹甲弾x1 ", Days = new string[] {"日","金","土"}, ShipName = "金剛"},
            new IATable { Equip = "一式徹甲弾", Info = "★0~5\t1+九一式徹甲弾x2/2+一式徹甲弾x1 ", Days = new string[] {"月","火","水"}, ShipName = "榛名"},
            //対空機銃
            new IATable { Equip = "25mm単装機銃", Info = "★0~5\t1/1+25mm単装機銃x1 /1+25mm単装機銃x1\t⇒25mm連装機銃★+5", Days = new string[] {"木"}, ShipName = "鬼怒"},
            new IATable { Equip = "25mm単装機銃", Info = "★0~5\t1/1+25mm単装機銃x1 /1+25mm単装機銃x1\t⇒25mm連装機銃★+5", Days = new string[] {"日","金","土"}, ShipName = "皐月"},
            new IATable { Equip = "25mm単装機銃", Info = "★0~5\t1/1+25mm単装機銃x1 /1+25mm単装機銃x1\t⇒25mm連装機銃★+5", Days = new string[] {"水","木","金","土"}, ShipName = "文月"},
            new IATable { Equip = "25mm連装機銃", Info = "★0~5\t1/1+25mm連装機銃x1 /1+25mm連装機銃x1\t⇒25mm三連装機銃★+3", Days = new string[] {"日","土"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "25mm連装機銃", Info = "★0~5\t1/1+25mm連装機銃x1 /1+25mm連装機銃x1\t⇒25mm三連装機銃★+3", Days = new string[] {"水"}, ShipName = "鬼怒"},
            new IATable { Equip = "25mm連装機銃", Info = "★0~5\t1/1+25mm連装機銃x1 /1+25mm連装機銃x1\t⇒25mm三連装機銃★+3", Days = new string[] {"月","火"}, ShipName = "皐月"},
            new IATable { Equip = "25mm連装機銃", Info = "★0~5\t1/1+25mm連装機銃x1 /1+25mm連装機銃x1\t⇒25mm三連装機銃★+3", Days = new string[] {"日","月","火"}, ShipName = "文月"},
            new IATable { Equip = "25mm三連装機銃", Info = "★0~5\t1/1+25mm三連装機銃x1 /3+25mm三連装機銃(5)\t⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"火","水","木"}, ShipName = "摩耶"},
            new IATable { Equip = "25mm三連装機銃", Info = "★0~5\t1/1+25mm三連装機銃x1 /3+25mm三連装機銃(5)\t⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"日","月","火","水","木"}, ShipName = "摩耶改二"},
            new IATable { Equip = "25mm三連装機銃", Info = "★0~5\t1/1+25mm三連装機銃x1 /3+25mm三連装機銃(5)\t⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"月","火","水"}, ShipName = "五十鈴改二"},
            new IATable { Equip = "25mm三連装機銃", Info = "★0~5\t1/1+25mm三連装機銃x1 /3+25mm三連装機銃(5)\t⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"月","火"}, ShipName = "鬼怒改二"},
            new IATable { Equip = "25mm三連装機銃", Info = "★0~5\t1/1+25mm三連装機銃x1 /3+25mm三連装機銃(5)\t⇒25mm三連装機銃 集中配備(摩耶改二/五十鈴改二/鬼怒改二/皐月改二)", Days = new string[] {"水","木"}, ShipName = "皐月改二"},
            new IATable { Equip = "25mm三連装機銃 集中配備", Info = "★0~5\t3+25mm三連装機銃x3/6+25mm三連装機銃(5)", Days = new string[] {"火","水","木"}, ShipName = "摩耶改二"},
            new IATable { Equip = "25mm三連装機銃 集中配備", Info = "★0~5\t3+25mm三連装機銃x3/6+25mm三連装機銃(5)", Days = new string[] {"日","金","土"}, ShipName = "鬼怒改二"},
            //高射装置
            new IATable { Equip = "91式高射装置", Info = "★0~5\t1+なし\n★6~9\t2+12.7cm連装高角砲x1\n★max\t4+10cm連装高角砲x2\t⇒94式高射装置", Days = new string[] {"日","月","金","土"}, ShipName = "摩耶"},
            new IATable { Equip = "91式高射装置", Info = "★0~5\t1+なし\n★6~9\t2+12.7cm連装高角砲x1\n★max\t4+10cm連装高角砲x2\t⇒94式高射装置", Days = new string[] {"日","月","金","土"}, ShipName = "秋月"},
            new IATable { Equip = "91式高射装置", Info = "★0~5\t1+なし\n★6~9\t2+12.7cm連装高角砲x1\n★max\t4+10cm連装高角砲x2\t⇒94式高射装置", Days = new string[] {"日","木","金","土"}, ShipName = "照月"},
            new IATable { Equip = "94式高射装置", Info = "★0~5\t2+なし\n★6~9\t3+10cm連装高角砲x1\n★max\t5+10cm連装高角砲x2\t⇒10cm高角砲+高射装置", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "秋月"},
            new IATable { Equip = "94式高射装置", Info = "★0~5\t2+なし\n★6~9\t3+10cm連装高角砲x1\n★max\t5+10cm連装高角砲x2\t⇒10cm高角砲+高射装置", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "照月"},
            new IATable { Equip = "94式高射装置", Info = "★0~5\t2+なし\n★6~9\t3+10cm連装高角砲x1\n★max\t5+10cm連装高角砲x2)\t⇒10cm高角砲+高射装置", Days = new string[] {"日","金","土"}, ShipName = "初月"},
            new IATable { Equip = "94式高射装置", Info = "★0~5\t2+なし\n★6~9\t3+10cm連装高角砲x1\n★max\t5+10cm連装高角砲x2)\t⇒10cm高角砲+高射装置", Days = new string[] {"日","月","金","土"}, ShipName = "涼月"},
            new IATable { Equip = "94式高射装置", Info = "★0~5\t2+なし\n★6~9\t3+10cm連装高角砲x1\n★max\t5+10cm連装高角砲x2\t⇒10cm高角砲+高射装置", Days = new string[] {"日","木","金","土"}, ShipName = "吹雪改二"},
            new IATable { Equip = "94式高射装置", Info = "★0~5\t2+なし\n★6~9\t3+12.7cm連装高角砲x1\n★max\t5+12.7cm連装高角砲x2\t⇒12.7cm高角砲+高射装置(摩耶改二)", Days = new string[] {"日","木","金","土"}, ShipName = "摩耶改二"},
            //上陸用舟艇・特型内火艇
            new IATable { Equip = "大発動艇", Info = "★0~5\t1+ドラム缶(輸送用)x1\n★6~9\t2+7.7mm機銃x1\n★max\t3+12.7mm単装機銃x3\t⇒大発動艇(八九式中戦車＆陸戦隊)\n★max\t6+同装備x4\t⇒特大発動艇\n★max\t大発動艇(八九式中戦車＆陸戦隊)x1\t⇒武装大発", Days = new string[] {"日","月","金","土"}, ShipName = "阿武隈改二"},
            new IATable { Equip = "大発動艇", Info = "★0~5\t1+ドラム缶(輸送用)x1\n★6~9\t2+7.7mm機銃x1\n★max\t3+12.7mm単装機銃x3\t⇒大発動艇(八九式中戦車＆陸戦隊)\n★max\t6+同装備x4\t⇒特大発動艇\n★max\t大発動艇(八九式中戦車＆陸戦隊)x1\t⇒武装大発", Days = new string[] {"日","月","火","水"}, ShipName = "皐月改二"},
            new IATable { Equip = "大発動艇", Info = "★0~5\t1+ドラム缶(輸送用)x1\n★6~9\t2+7.7mm機銃x1\n★max\t3+12.7mm単装機銃x3\t⇒大発動艇(八九式中戦車＆陸戦隊)\n★max\t6+同装備x4\t⇒特大発動艇\n★max\t大発動艇(八九式中戦車＆陸戦隊)x1\t⇒武装大発", Days = new string[] {"日","水","木","金","土"}, ShipName = "あきつ丸"},
            new IATable { Equip = "大発動艇", Info = "★0~5\t1+ドラム缶(輸送用)x1\n★6~9\t2+7.7mm機銃x1\n★max\t6+同装備x4\t⇒特大発動艇", Days = new string[] { "月","火","水","木"}, ShipName = "龍田改二"},
            new IATable { Equip = "大発動艇", Info = "★0~5\t1+ドラム缶(輸送用)x1\n★6~9\t2+7.7mm機銃x1\n★max\t6+同装備x4\t⇒特大発動艇", Days = new string[] {"日","水","木","金","土"}, ShipName = "鬼怒改二"},
            new IATable { Equip = "大発動艇", Info = "★0~5\t1+ドラム缶(輸送用)x1\n★6~9\t2+7.7mm機銃x1\n★max\t大発動艇(八九式中戦車＆陸戦隊)x1\t⇒武装大発", Days = new string[] {"日","月","火","水"}, ShipName = "浦波改二"},
            new IATable { Equip = "大発動艇", Info = "★0~5\t1+ドラム缶(輸送用)x1\n★6~9\t2+7.7mm機銃x1\n★max\t大発動艇(八九式中戦車＆陸戦隊)x1\t⇒武装大発", Days = new string[] {"日","水","木","金","土"}, ShipName = "神州丸"},
            new IATable { Equip = "大発動艇(八九式中戦車&陸戦隊)", Info = "★0~5\t2+25mm単装機銃x1\n★6~9\t3+12cm30連装噴進砲x2\n★max\t5+7.7mm機銃x3\t⇒特二式内火艇", Days = new string[] {"火","水","木"}, ShipName = "阿武隈改二"},
            new IATable { Equip = "大発動艇(八九式中戦車&陸戦隊)", Info = "★0~5\t2+25mm単装機銃x1\n★6~9\t3+12cm30連装噴進砲x2\n★max\t5+7.7mm機銃x3\t⇒特二式内火艇", Days = new string[] {"木","金","土"}, ShipName = "皐月改二"},
            new IATable { Equip = "大発動艇(八九式中戦車&陸戦隊)", Info = "★0~5\t2+25mm単装機銃x1\n★6~9\t3+12cm30連装噴進砲x2\n★max\t5+7.7mm機銃x3\t⇒特二式内火艇", Days = new string[] {"日","月","金","土"}, ShipName = "あきつ丸"},
            new IATable { Equip = "特大発動艇", Info = "★0~5\t2+ドラム缶(輸送用)x2\n★6~9\t4+大発動艇x1", Days = new string[] {"日","月","金","土"}, ShipName = "鬼怒改二"},
            new IATable { Equip = "特大発動艇", Info = "★0~5\t2+ドラム缶(輸送用)x2\n★6~9\t4+大発動艇x1", Days = new string[] {"火","水","木"}, ShipName = "あきつ丸"},
            new IATable { Equip = "武装大発", Info = "★0~5\t3+12.7mm単装機銃x1\n★6~9\t4+二式12cm迫撃砲改x1", Days = new string[] {"日","木","金","土"}, ShipName = "神州丸"},
            new IATable { Equip = "装甲艇(AB艇)", Info = "★0~5\t2+25mm単装機銃x1\n★6~9\t3+二式12cm迫撃砲改x1", Days = new string[] {"月","火","水"}, ShipName = "神州丸"},
            new IATable { Equip = "特二式内火艇", Info = "★0~5\t3+7.7mm機銃x2\n★6~9\t4+12.7mm単装機銃x3", Days = new string[] {"水","木","金","土"}, ShipName = "伊8"},
            new IATable { Equip = "特二式内火艇", Info = "★0~5\t3+7.7mm機銃x2\n★6~9\t4+12.7mm単装機銃x3", Days = new string[] {"日","月","金","土"}, ShipName = "伊58"},
            new IATable { Equip = "特二式内火艇", Info = "★0~5\t3+7.7mm機銃x2\n★6~9\t4+12.7mm単装機銃x3", Days = new string[] {"月","火","水","木"}, ShipName = "伊401"},
            //対地装備
            new IATable { Equip = "艦載型 四式20cm対地噴進砲", Info = "★0~5\t3+ドラム缶(輸送用)x1\n★6~9\t4+12cm30連装噴進砲x1\n★max\t7+同装備x1+新型噴進装備開発資材x2\t⇒四式20cm対地噴進砲 集中配備", Days = new string[] {"月","火","水","木",}, ShipName = "秋津洲改"},
            new IATable { Equip = "艦載型 四式20cm対地噴進砲", Info = "★0~5\t3+ドラム缶(輸送用)x1\n★6~9\t4+12cm30連装噴進砲x1\n★max\t7+同装備x1+新型噴進装備開発資材x2\t⇒四式20cm対地噴進砲 集中配備", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "大潮改二"},
            new IATable { Equip = "艦載型 四式20cm対地噴進砲", Info = "★0~5\t3+ドラム缶(輸送用)x1\n★6~9\t4+12cm30連装噴進砲x1\n★max\t7+同装備x1+新型噴進装備開発資材x2\t⇒四式20cm対地噴進砲 集中配備", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "荒潮改二"},
            //探照灯
            new IATable { Equip = "探照灯", Info = "★0~5\t2+なし\n★6~9\t2+同装備x1\n★max\t3+熟練見張員x1\t⇒96式150cm探照灯", Days = new string[] {"月","火","水"}, ShipName = "青葉"},
            new IATable { Equip = "探照灯", Info = "★0~5\t2+なし\n★6~9\t2+同装備x1 3+熟練見張員x1\t⇒96式150cm探照灯", Days = new string[] {"月","火","水"}, ShipName = "綾波"},
            new IATable { Equip = "探照灯", Info = "★0~5\t2+なし\n★6~9\t2+同装備x1 3+熟練見張員x1\t⇒96式150cm探照灯", Days = new string[] {"日", "月","金","土"}, ShipName = "鳥海"},
            new IATable { Equip = "探照灯", Info = "★0~5\t2+なし\n★6~9\t2+同装備x1 3+熟練見張員x1\t⇒96式150cm探照灯", Days = new string[] {"日","金","土"}, ShipName = "神通"},
            new IATable { Equip = "探照灯", Info = "★0~5\t2+なし\n★6~9\t2+同装備x1 3+熟練見張員x1\t⇒96式150cm探照灯", Days = new string[] {"木","金","土"}, ShipName = "暁"},
            new IATable { Equip = "探照灯", Info = "★0~5\t2+なし\n★6~9\t2+同装備x1 3+熟練見張員x1\t⇒96式150cm探照灯", Days = new string[] {"日", "月","火","水","木","金","土"}, ShipName = "秋雲"},
            new IATable { Equip = "96式150cm探照灯", Info = "★0~5\t3+探照灯x1\n★6~9\t3+探照灯x1", Days = new string[] {"日","月","金","土"}, ShipName = "比叡"},
            new IATable { Equip = "96式150cm探照灯", Info = "★0~5\t3+探照灯x1\n★6~9\t3+探照灯x1", Days = new string[] {"火","水","木","金"}, ShipName = "霧島"},
            //増設バルジ
            new IATable { Equip = "増設バルジ(中型艦)", Info = "★0~5\t4+同装備x1\n★6~9\t6+同装備x2\n★max\t8+同装備x3\t⇒艦本新設計 増設バルジ(中型艦)", Days = new string[] {"月","火","水"}, ShipName = "Zara due"},
            new IATable { Equip = "増設バルジ(中型艦)", Info = "★0~5\t4+同装備x1\n★6~9\t6+同装備x2\n★max\t8+同装備x3\t⇒艦本新設計 増設バルジ(中型艦)", Days = new string[] {"月","火","水","木"}, ShipName = "酒匂"},
            new IATable { Equip = "増設バルジ(中型艦)", Info = "★0~5\t4+同装備x1\n★6~9\t6+同装備x2\n★max\t8+同装備x3\t⇒艦本新設計 増設バルジ(中型艦)", Days = new string[] {"日","月","火","水"}, ShipName = "Верный"},
            new IATable { Equip = "艦本新設計 増設バルジ(中型艦)", Info = "★0~5\t6+増設バルジ(中型艦)x2\n★6~9\t8+増設バルジ(中型艦)x3", Days = new string[] {"火","水","木"}, ShipName = "Zara due"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "★0~5\t4+増設バルジ(中型艦)x2\n★6~9\t6+同装備x1\n★max\t8+同装備x2\t⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"木","金","土"}, ShipName = "長門"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "★0~5\t4+増設バルジ(中型艦)x2\n★6~9\t6+同装備x1\n★max\t8+同装備x2\t⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"木","金","土"}, ShipName = "武蔵"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "★0~5\t4+増設バルジ(中型艦)x2\n★6~9\t6+同装備x1\n★max\t8+同装備x2\t⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"水","木","金"}, ShipName = "陸奥"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "★0~5\t4+増設バルジ(中型艦)x2\n★6~9\t6+同装備x1\n★max\t8+同装備x2\t⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"水","木","金"}, ShipName = "大和"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "★0~5\t4+増設バルジ(中型艦)x2\n★6~9\t6+同装備x1\n★max\t8+同装備x2\t⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"月","火"}, ShipName = "陸奥改二"},
            new IATable { Equip = "増設バルジ(大型艦)", Info = "★0~5\t4+増設バルジ(中型艦)x2\n★6~9\t6+同装備x1\n★max\t8+同装備x2\t⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"金"}, ShipName = "大和改二"},
            new IATable { Equip = "艦本新設計 増設バルジ(大型艦)", Info = "★0~5\t4+増設バルジ(中型艦)x2\n★6~9\t6+同装備x1x1 7+381mm/50 三連装砲x1\t⇒艦本新設計 増設バルジ(大型艦)", Days = new string[] {"月","火","水","木"}, ShipName = "Conte di Cavour"},
            new IATable { Equip = "艦本新設計 増設バルジ(大型艦)", Info = "★0~5\t6+増設バルジ(大型艦)x1\n★6~9\t8+増設バルジ(大型艦)x2", Days = new string[] {"日","土"}, ShipName = "大和"},
            new IATable { Equip = "艦本新設計 増設バルジ(大型艦)", Info = "★0~5\t6+増設バルジ(大型艦)x1\n★6~9\t8+増設バルジ(大型艦)x2", Days = new string[] {"日","火"}, ShipName = "武蔵"},
            new IATable { Equip = "艦本新設計 増設バルジ(大型艦)", Info = "★0~5\t6+増設バルジ(大型艦)x1\n★6~9\t8+増設バルジ(大型艦)x2", Days = new string[] {"月"}, ShipName = "武蔵改二"},
            new IATable { Equip = "プリエーゼ式水中防御隔壁", Info = "★0~5\t4+増設バルジ(大型艦)x1\n★6~9\t6+同装備x1", Days = new string[] {"火","水","木"}, ShipName = "Littorio"},
            new IATable { Equip = "プリエーゼ式水中防御隔壁", Info = "★0~5\t4+増設バルジ(大型艦)x1\n★6~9\t6+同装備x1", Days = new string[] {"月","火","水","木"}, ShipName = "Conte di Cavour nuovo"},
            //機関部強化
            new IATable { Equip = "強化型艦本式缶", Info = "★0~5\t5+改良型艦本式タービンx1\n★6~9\t7+同装備x1\n★max\t8+同装備x2\t⇒新型高温高圧缶", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "天津風"},
            new IATable { Equip = "強化型艦本式缶", Info = "★0~5\t5+改良型艦本式タービンx1\n★6~9\t7+同装備x1\n★max\t8+同装備x2\t⇒新型高温高圧缶", Days = new string[] {"火","水"}, ShipName = "島風"},
            new IATable { Equip = "新型高温高圧缶", Info = "★0~5\t8+改良型艦本式タービンx2\n★6~9\t9+強化型艦本式缶x2", Days = new string[] {"火","水","木"}, ShipName = "天津風改"},
            new IATable { Equip = "新型高温高圧缶", Info = "★0~5\t8+改良型艦本式タービンx2\n★6~9\t9+強化型艦本式缶x2", Days = new string[] {"月","火","金"}, ShipName = "島風"},
            //潜水艦装備
            new IATable { Equip = "潜水艦搭載電探&水防式望遠鏡", Info = "★0~5\t7+22号対水上電探x2\n★6~9\t8+熟練見張員x1\n★max\t10+13号対空電探改x3+型兵装資材x1\t⇒潜水艦搭載電探＆逆探(E27)", Days = new string[] {"月","火","水","木"}, ShipName = "伊401"},
            new IATable { Equip = "潜水艦搭載電探&水防式望遠鏡", Info = "★0~5\t7+22号対水上電探x2\n★6~9\t8+熟練見張員x1\n★max\t10+13号対空電探改x3+型兵装資材x1\t⇒潜水艦搭載電探＆逆探(E27)", Days = new string[] {"火","水","木","金"}, ShipName = "伊8"},
            //戦闘糧食
            new IATable { Equip = "戦闘糧食", Info = "★0~5\t0+同装備x1\n★6~9\t1+なし\n★max\t0+同装備x1\t⇒戦闘糧食(特別なおにぎり)", Days = new string[] {"日","金","土"}, ShipName = "阿賀野"},
            new IATable { Equip = "戦闘糧食", Info = "★0~5\t0+同装備x1\n★6~9\t1+なし\n★max\t0+同装備x1\t⇒戦闘糧食(特別なおにぎり)", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "長波"},
            //航空要員

            //陸上攻撃機
            new IATable { Equip = "九六式陸攻", Info = "★0~5\t3+九六式艦戦x1\n★6~9\t3+九七式艦攻x1\n★max\t4+九九式艦爆x2\t⇒一式陸攻", Days = new string[] {"日","木","金","土"}, ShipName = "扶桑"},
            new IATable { Equip = "一式陸攻", Info = "★0~5\t3+九六式艦戦x1\n★6~9\t3+九七式艦攻x1\n★max\t4+九九式艦爆x2\t⇒一式陸攻 二二型甲", Days = new string[] {"日","木","金","土"}, ShipName = "山城"},
            new IATable { Equip = "一式陸攻 二二型甲", Info = "★0~5\t3+九六式艦戦x1\n★6~9\t3+九七式艦攻x1\n★max\t4+九九式艦爆x2\t⇒一式陸攻 三四型", Days = new string[] {"日","木","金","土"}, ShipName = "霧島"},
            new IATable { Equip = "一式陸攻 三四型", Info = "★0~5\t3+九六式艦戦x1\n★6~9\t3+九七式艦攻x1\n★max\t4+九九式艦爆x2", Days = new string[] {"日","木","金","土"}, ShipName = "榛名"},
            new IATable { Equip = "爆装一式戦 隼III型改(65戦隊)", Info = "★0~5\t4+彗星x2\n★6~9\t6+流星x2", Days = new string[] {"水","木","金","土"}, ShipName = "神威"},
            new IATable { Equip = "四式重爆 飛龍", Info = "★0~5\t5+天山x11\n★6~9\t6+一式陸攻x1\n★max\t8+一式陸攻 二二型甲x1+新型航空兵装資材x3+熟練搭乗員x3\t⇒四式重爆 飛龍(熟練)", Days = new string[] {"日","木","金","土"}, ShipName = "神州丸"},
            new IATable { Equip = "Do 17 Z-2", Info = "★0~5\t3+九七式艦攻x1\n★6~9\t5+九六式陸攻x1\n★max\t11+一式陸攻x3+新型航空兵装資材x4+新型兵装資材x2\t⇒Do 217 E-5＋Hs293初期型", Days = new string[] {"日","月","金","土"}, ShipName = "Bismarck"},
            new IATable { Equip = "Do 17 Z-2", Info = "★0~5\t3+九七式艦攻x1\n★6~9\t5+九六式陸攻x1\n★max\t11+一式陸攻x3+新型航空兵装資材x4+新型兵装資材x2\t⇒Do 217 E-5＋Hs293初期型", Days = new string[] {"火","水"}, ShipName = "Prinz Eugen改"},
            //陸軍戦闘機
            new IATable { Equip = "一式戦 隼II型", Info = "★0~5\t2+九六式艦戦x1 /3+零式艦戦21型x2/6+12.7mm単装機銃x3+新型航空兵装資材x1\t⇒一式戦 隼III型甲", Days = new string[] {"月","火","水","木"}, ShipName = "春日丸"},
            new IATable { Equip = "一式戦 隼II型", Info = "★0~5\t2+九六式艦戦x1 /3+零式艦戦21型x2/6+12.7mm単装機銃x3+新型航空兵装資材x1\t⇒一式戦 隼III型甲", Days = new string[] {"月","火","水","木"}, ShipName = "あきつ丸"},
            new IATable { Equip = "一式戦 隼II型", Info = "★0~5\t2+九六式艦戦x1 /3+零式艦戦21型x2/6+12.7mm単装機銃x3+新型航空兵装資材x1\t⇒一式戦 隼III型甲", Days = new string[] {"水","木","金"}, ShipName = "神威"},
            new IATable { Equip = "一式戦 隼III型甲", Info = "★0~5\t4+零式艦戦52型x3/6+烈風x2", Days = new string[] {"月","火"}, ShipName = "あきつ丸"},
            new IATable { Equip = "一式戦 隼III型甲", Info = "★0~5\t4+零式艦戦52型x3/6+烈風x2", Days = new string[] {"月","火","水","木"}, ShipName = "春日丸"},
            new IATable { Equip = "一式戦 隼III型甲", Info = "★0~5\t4+零式艦戦52型x3/6+烈風x2", Days = new string[] {"木","金"}, ShipName = "神威"},
            //局地戦闘機
            new IATable { Equip = "紫電一一型", Info = "★0~5\t4+零式艦戦52型x2\n★6~9\t6+瑞雲x2\n★max\t7+紫電改二x2\t⇒紫電二一型 紫電改", Days = new string[] {"月","火","水"}, ShipName = "赤城"},
            new IATable { Equip = "紫電一一型", Info = "★0~5\t4+零式艦戦52型x2\n★6~9\t6+瑞雲x2\n★max\t7+紫電改二x2\t⇒紫電二一型 紫電改", Days = new string[] {"月","火","水"}, ShipName = "加賀"},
            new IATable { Equip = "紫電二一型 紫電改", Info = "★0~5\t4+紫電改二x1\n★6~9\t6+紫電一一型x1\n★max\t13+紫電二一型 紫電改x2+戦闘詳報x1+熟練搭乗員x1\t⇒紫電改(三四三空) 戦闘301", Days = new string[] {"火","水"}, ShipName = "榛名"},
            //回転翼機
            new IATable { Equip = "カ号観測機", Info = "★0~5\t2+なし\n★6~9\t3+零式水上偵察機x1\n★max\t5+同装備x1+新型航空兵装資材x1\t⇒オ号観測機改", Days = new string[] {"水","木"}, ShipName = "伊勢改二"},
            new IATable { Equip = "オ号観測機改", Info = "★0~5\t3+なし\n★6~9\t4+九六式艦戦x1\n★max\t7+カ号観測機x1+新型航空兵装資材x1\t⇒オ号観測機改二", Days = new string[] {"月","火"}, ShipName = "日向改二"},
            new IATable { Equip = "オ号観測機改二", Info = "★0~5\t4+零式水上偵察機x1\n★6~9\t5+九九式艦爆x2\n★max\t10+同装備x1+新型航空兵装資材x3\t⇒S-51J", Days = new string[] {"水","木","金"}, ShipName = "日向改二"},
            new IATable { Equip = "S-51J", Info = "★0~5\t7+瑞雲x1\n★6~9\t7+彩雲x1\n★max\t10+九五式爆雷x2+新型航空兵装資材x1\t⇒S-51J改", Days = new string[] {"日","土"}, ShipName = "日向改二"},
            new IATable { Equip = "S-51J改", Info = "★0~5\t8+瑞雲x2\n★6~9\t8+三式爆雷投射機x2", Days = new string[] {"日","土"}, ShipName = "日向改二"},
            //対潜哨戒機
            new IATable { Equip = "三式指揮連絡機(対潜)", Info = "★0~5\t2+九七式艦攻x1\n★6~9\t3+同装備x1\n★max\t7+カ号観測機x2+新型航空兵装資材x1\t⇒三式指揮連絡機改", Days = new string[] {"日","月","火","水","木","金","土"}, ShipName = "山汐丸"},
            new IATable { Equip = "三式指揮連絡機改", Info = "★0~5\t2+三式指揮連絡機(対潜)x1\n★6~9\t4+カ号観測機x1", Days = new string[] {"水","木","金","土"}, ShipName = "山汐丸"},
        };
    }
}

